export const ERROR_CODES = {
  INTERNAL_ERROR: "INTERNAL_ERROR",
  VALIDATION_ERROR: "VALIDATION_ERROR",
  NOT_FOUND: "NOT_FOUND",
  DUPLICATE_RESOURCE: "DUPLICATE_RESOURCE",
  UNAUTHORIZED: "UNAUTHORIZED",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  SESSION_EXPIRED: "SESSION_EXPIRED",
  FORBIDDEN: "FORBIDDEN",
  BUSINESS_ACCESS_DENIED: "BUSINESS_ACCESS_DENIED",
  BUSINESS_CONTEXT_REQUIRED: "BUSINESS_CONTEXT_REQUIRED",
  INSUFFICIENT_PERMISSIONS: "INSUFFICIENT_PERMISSIONS",
  USER_NOT_FOUND: "USER_NOT_FOUND",
  EMAIL_CONFLICT: "EMAIL_CONFLICT",
  PHONE_CONFLICT: "PHONE_CONFLICT",
  BAD_REQUEST: "BAD_REQUEST",
  DUPLICATE_REQUEST_IN_PROGRESS: "DUPLICATE_REQUEST_IN_PROGRESS",
  INVOICE_TOTAL_MISMATCH: "INVOICE_TOTAL_MISMATCH",
  STOCK_INSUFFICIENT: "STOCK_INSUFFICIENT",
  PARTY_NOT_FOUND: "PARTY_NOT_FOUND",
  INVOICE_NOT_FOUND: "INVOICE_NOT_FOUND",
  INVENTORY_ITEM_NOT_FOUND: "INVENTORY_ITEM_NOT_FOUND",
  INVOICE_ALREADY_CANCELLED: "INVOICE_ALREADY_CANCELLED",
  INVOICE_CANCEL_NOT_ALLOWED: "INVOICE_CANCEL_NOT_ALLOWED",
  PAYMENT_NOT_FOUND: "PAYMENT_NOT_FOUND",
  PAYMENT_ALREADY_RECONCILED: "PAYMENT_ALREADY_RECONCILED",
  PAYMENT_NOT_RECONCILED: "PAYMENT_NOT_RECONCILED",
  OPTIMISTIC_CONFLICT: "OPTIMISTIC_CONFLICT",
} as const;

export type ErrorCode = (typeof ERROR_CODES)[keyof typeof ERROR_CODES];

// User-friendly error messages
export const ERROR_MESSAGES: Record<ErrorCode, string> = {
  [ERROR_CODES.INTERNAL_ERROR]: "Something went wrong. Please try again later.",
  [ERROR_CODES.VALIDATION_ERROR]: "Please check your input and try again.",
  [ERROR_CODES.NOT_FOUND]: "The requested resource was not found.",
  [ERROR_CODES.DUPLICATE_RESOURCE]: "This resource already exists.",
  [ERROR_CODES.UNAUTHORIZED]: "You need to be logged in to access this.",
  [ERROR_CODES.INVALID_CREDENTIALS]: "Invalid email/phone or password.",
  [ERROR_CODES.SESSION_EXPIRED]: "Your session has expired. Please login again.",
  [ERROR_CODES.FORBIDDEN]: "You don't have permission to perform this action.",
  [ERROR_CODES.BUSINESS_ACCESS_DENIED]: "You don't have access to this business.",
  [ERROR_CODES.BUSINESS_CONTEXT_REQUIRED]: "Please select a business to continue.",
  [ERROR_CODES.INSUFFICIENT_PERMISSIONS]: "You don't have sufficient permissions.",
  [ERROR_CODES.USER_NOT_FOUND]: "User not found.",
  [ERROR_CODES.EMAIL_CONFLICT]: "This email is already registered.",
  [ERROR_CODES.PHONE_CONFLICT]: "This phone number is already registered.",
  [ERROR_CODES.BAD_REQUEST]: "Invalid request. Please check your input.",
  [ERROR_CODES.DUPLICATE_REQUEST_IN_PROGRESS]: "A similar request is already in progress.",
  [ERROR_CODES.INVOICE_TOTAL_MISMATCH]: "Invoice total doesn't match the items.",
  [ERROR_CODES.STOCK_INSUFFICIENT]: "Insufficient stock available.",
  [ERROR_CODES.PARTY_NOT_FOUND]: "Party not found.",
  [ERROR_CODES.INVOICE_NOT_FOUND]: "Invoice not found.",
  [ERROR_CODES.INVENTORY_ITEM_NOT_FOUND]: "Inventory item not found.",
  [ERROR_CODES.INVOICE_ALREADY_CANCELLED]: "This invoice is already cancelled.",
  [ERROR_CODES.INVOICE_CANCEL_NOT_ALLOWED]: "This invoice cannot be cancelled.",
  [ERROR_CODES.PAYMENT_NOT_FOUND]: "Payment not found.",
  [ERROR_CODES.PAYMENT_ALREADY_RECONCILED]: "This payment is already reconciled.",
  [ERROR_CODES.PAYMENT_NOT_RECONCILED]: "This payment is not reconciled.",
  [ERROR_CODES.OPTIMISTIC_CONFLICT]: "This resource was modified by another user. Please refresh and try again.",
};
